### PR TITLE
Get correct filesystem deployment file for Dockerfile generation

### LINKED ISSUE #564: Dockerfile generation doesn't work for filesystem deployment sources
If the user selects a filesystem deployment source, the Dockerfile generation doesn't work. It attempts to call deploymentSource.getFile() but there is no file set for this custom deployment source type since the file gets created later (when the user browses to one).

### PR DESCRIPTION
**Pull request by etanshaul**
fixes #564

### CODE REVIEW

**Comment by etanshaul** [comment]
@chanseokoh @elharo ptal

File: google-cloud-tools-plugin/src/com/google/gct/idea/appengine/cloud/AppEngineDeploymentRunConfigurationEditor.java [hunk 1]
```diff
@@ -134,8 +135,14 @@ public File get() {
         new GenerateConfigActionListener(project, "Dockerfile", new Supplier<File>() {
           @Override
           public File get() {
+            File deploymentFile;
+            if(deploymentSource.getType() instanceof UserSpecifiedPathDeploymentSourceType) {
+              deploymentFile = new File(userSpecifiedArtifactFileSelector.getText());
```
Comment (patflynn) [inline google-cloud-tools-plugin/src/com/google/gct/idea/appengine/cloud/AppEngineDeploymentRunConfigurationEditor.java]: could we not have the UserSpecifiedPathdDeploymentSourceType implement getFile correctly?

Comment (etanshaul) [inline google-cloud-tools-plugin/src/com/google/gct/idea/appengine/cloud/AppEngineDeploymentRunConfigurationEditor.java]: The problem is that we don't know what to return from getFile: this only gets determined when a user manually browses to one. We could manually set it, e.g. add state to the class. But I'm not sure if thats better.

Comment (etanshaul) [inline google-cloud-tools-plugin/src/com/google/gct/idea/appengine/cloud/AppEngineDeploymentRunConfigurationEditor.java]: What I mean is, we could override getFile and have it return an internal state that we manually set whenever a user browses to a filesystem jar/war. Do you like that approach better?

Comment (patflynn) [inline google-cloud-tools-plugin/src/com/google/gct/idea/appengine/cloud/AppEngineDeploymentRunConfigurationEditor.java]: That is kind of what I expect the DeploymentSource contract is asking our
implementation to do.

**Comment by chanseokoh** [comment]
LGTM.

**Comment by etanshaul** [comment]
@patflynn updated to use DeploymentSource getFile

File: google-cloud-tools-plugin/src/com/google/gct/idea/appengine/cloud/AppEngineCloudType.java [hunk 2]
```diff
@@ -202,6 +203,16 @@ public void setName(String name) {
         this.name = name;
       }
 
+      @Nullable
+      @Override
+      public File getFile() {
+        return new File(userSpecifiedFilePath);
```
Comment (patflynn) [inline google-cloud-tools-plugin/src/com/google/gct/idea/appengine/cloud/AppEngineCloudType.java]: should this return null if userSpecifiedfilePath is not set?

Comment (etanshaul) [inline google-cloud-tools-plugin/src/com/google/gct/idea/appengine/cloud/AppEngineCloudType.java]: I think if the userSpecifiedFilePath is not set then the fix that @chanseokoh is working on (#560) should prevent the custom deployment UI from being shown in the first place.

Comment (chanseokoh) [inline google-cloud-tools-plugin/src/com/google/gct/idea/appengine/cloud/AppEngineCloudType.java]: Regarding #560, even if the userSpecifiedFilePath is set, if that path does not end with either .jar or .war, then Dockerfile auto-generation will still produce an error. For this reason, I am not working on showing/hiding the custom deployment UI, but rather working on displaying an error message dialog.

Comment (etanshaul) [inline google-cloud-tools-plugin/src/com/google/gct/idea/appengine/cloud/AppEngineCloudType.java]: @chanseokoh Maybe I'm not understanding, but couldn't you only show the custom config if the path is set AND is a jar/war (currently the validation ensures that it has a .jar/.war extension)?

Comment (etanshaul) [inline google-cloud-tools-plugin/src/com/google/gct/idea/appengine/cloud/AppEngineCloudType.java]: As a side note, I think adding an error dialog into the mix would be a bit odd since we are already showing label error messages. So having the one off dialog may feel strange.

**Comment by etanshaul** [comment]
@patflynn ptal. I updated to better satisfy the @Nullable contract of getFile()

File: google-cloud-tools-plugin/src/com/google/gct/idea/appengine/cloud/DeploymentArtifactType.java [hunk 3]
```diff
@@ -31,11 +32,13 @@
    * Returns the right {@code DeploymentArtifactType} for the given {@code deployPackage}.
    */
   @NotNull
-  public static DeploymentArtifactType typeForPath(@NotNull File deployPackage) {
-    if (deployPackage.getPath().endsWith(".jar")) {
-      return JAR;
-    } else if (deployPackage.getPath().endsWith(".war")) {
-      return WAR;
+  public static DeploymentArtifactType typeForPath(@Nullable File deployPackage) {
```
Comment (patflynn) [inline google-cloud-tools-plugin/src/com/google/gct/idea/appengine/cloud/DeploymentArtifactType.java]: apologies for flip flopping, but couldn't we leave this as @NotNull and just have the callers of this method handle the case where deploymenttSource.getFile == null?

**Comment by patflynn** [comment]
LGTM

File: google-cloud-tools-plugin/src/com/google/gct/idea/appengine/cloud/DeploymentArtifactType.java (hunk 3 above)
Comment (etanshaul) [inline google-cloud-tools-plugin/src/com/google/gct/idea/appengine/cloud/DeploymentArtifactType.java]: looking at the usages I think it makes sense to let it handle the nulls rather than the callers. The callers are already handling DeploymentArtifactType.UNKNOWN when needed, so my thinking is to just let null just be treated like another unknown type. Let me know if you disagree.

Comment (patflynn) [inline google-cloud-tools-plugin/src/com/google/gct/idea/appengine/cloud/DeploymentArtifactType.java]: OK. LGTM
