### PR TITLE
Register breakpoints only once. Some code style changes too.

### LINKED ISSUE #142: Closing and returning to a cloud debug session with a breakpoint that has been hit results in a duplicate 'open' breakpoint
steps to reproduce:
1) Start a cloud debug session based off of this doc https://docs.google.com/document/d/1cM1m6yHask_xnZ2E-L0gjo98aPbOWziFnwiK_ZKxzTw/edit#
2) Set a watchpoint
3) Click the red square and end your cloud debug session
4) Select Continue in the dialog that pops up
5) Trigger http://cloud-debugger-demo.appspot.com/gen
6) notice that you will be notified with a link to resume your session
7) note that your captured watchpoint is there, but also a duplicate of that watchpoint in un-hit state has been added.

expected outcome:
Only one watchpoint snapshot is displayed and it's in disabled state

### PR DESCRIPTION
**Pull request by joaoandremartins**
@elharo @patflynn fixes #142

### CODE REVIEW

File: core-plugin/src/com/google/gct/idea/debugger/CloudBreakpointHandler.java [hunk 1]
```diff
@@ -49,22 +49,27 @@
...
- * This class is threadsafe. All operations can be called by multiple threads.
- * <p/>
- * Note there are three breakpoint types managed in the debugger and are named to avoid confusion:
- * xIdeBreakpoint : these are {@link XBreakpoint} types that intelliJ defines and are sealed.
- * cloudIdeBreakpoint: these are our IDE defined customized breakpoints
- *                 {@link com.google.gct.idea.debugger.CloudLineBreakpointType.CloudLineBreakpoint} with
- *                 custom properties, etc. It's confusing that there are two hierarchies for IDE breakpoints,
- *                 but intelliJ does this to control some base behavior.
- * serverBreakpoint: these are the {@link Breakpoint} breakpoints our server gives us via the apiary api.
+ * The Cloud Debugger breakpoint handler is responsible for creating or deleting the breakpoints on
```
Comment (patflynn) [inline core-plugin/src/com/google/gct/idea/debugger/CloudBreakpointHandler.java]: can you call out if there are any actual text changes here apart from the reformat?

File: core-plugin/src/com/google/gct/idea/debugger/CloudBreakpointHandler.java [hunk 2]
```diff
@@ -49,22 +49,27 @@
...
+ * <ul>
+ * <li>xIdeBreakpoint : these are {@link XBreakpoint} types that intelliJ defines and are sealed.
+ * <li>cloudIdeBreakpoint: these are our IDE defined customized breakpoints
+ *                 {@link com.google.gct.idea.debugger.CloudLineBreakpointType.CloudLineBreakpoint}
+ *                 with custom properties, etc. It's confusing that there are two hierarchies for
+ *                 IDE breakpoints, but intelliJ does this to control some base behavior.
+ * <li>serverBreakpoint: these are the {@link Breakpoint} breakpoints our server gives us via the
+ *                 client api.
  */
-public class CloudBreakpointHandler extends XBreakpointHandler<XLineBreakpoint<CloudLineBreakpointProperties>> {
```
Comment (patflynn) [inline core-plugin/src/com/google/gct/idea/debugger/CloudBreakpointHandler.java]: what line length are you at?

**Comment by patflynn** [comment]
It'd be a lot easier to review this if the formatting changes were broken into another PR.

What style are you using for the basis of your reformat?

File: core-plugin/src/com/google/gct/idea/debugger/CloudBreakpointHandler.java (hunk 1 above)
Comment (joaoandremartins) [inline core-plugin/src/com/google/gct/idea/debugger/CloudBreakpointHandler.java]: None whatsoever. The only changes I applied were wrapping every line at 100 or less characters.

File: core-plugin/src/com/google/gct/idea/debugger/CloudBreakpointHandler.java (hunk 2 above)
Comment (joaoandremartins) [inline core-plugin/src/com/google/gct/idea/debugger/CloudBreakpointHandler.java]: 100, as per Google Java code style guidelines.

File: core-plugin/src/com/google/gct/idea/debugger/CloudBreakpointHandler.java [hunk 3]
```diff
@@ -78,13 +83,16 @@ public CloudBreakpointHandler(@NotNull CloudDebugProcess process) {
...
-   * 1. It only operates on final state breakpoints.
-   * 2. It always clones them into a new IDE breakpoint
-   * 3. It does not set "created by server = true", so when control flow comes back into register,
-   *    it will register with the server.
+   * Called when the user "reactivates" an existing snapshot to create a new breakpoint, this clones
+   * state into a new breakpoint. It is different from "createIdeRepresentationsIfNecessary" in the
+   * following respects:
+   *
+   * <ul>
+   * <li>1. It only operates on final state breakpoints.
```
Comment (elharo) [inline core-plugin/src/com/google/gct/idea/debugger/CloudBreakpointHandler.java]: no need for numbers with <li>; just use an <ol>

File: core-plugin/src/com/google/gct/idea/debugger/CloudBreakpointHandler.java [hunk 4]
```diff
@@ -78,13 +83,16 @@ public CloudBreakpointHandler(@NotNull CloudDebugProcess process) {
...
+   * <li>2. It always clones them into a new IDE breakpoint
```
Comment (elharo) [inline core-plugin/src/com/google/gct/idea/debugger/CloudBreakpointHandler.java]: nit: period

File: core-plugin/src/com/google/gct/idea/debugger/CloudBreakpointHandler.java [hunk 5]
```diff
@@ -425,8 +454,9 @@ public void run() {
   }
 
   @Override
-  public void unregisterBreakpoint(@NotNull XLineBreakpoint<CloudLineBreakpointProperties> xIdeBreakpoint,
-                                   boolean temporary) {
+  public void unregisterBreakpoint(
+      @NotNull XLineBreakpoint<CloudLineBreakpointProperties> xIdeBreakpoint,
+      boolean temporary) {
```
Comment (elharo) [inline core-plugin/src/com/google/gct/idea/debugger/CloudBreakpointHandler.java]: indent

**Comment by joaoandremartins** [comment]
I'm using the Google Java code style. Is that OK?

You're right that the style changes are taking up a considerable chunk of the diff, sorry for the mess. However, I thought that the effort of moving them to a new PR wasn't really worth it. Eventually, I think we should have one initiative dedicated to fixing the code style. But if we do some basic cosmetic changes on each PR, it will make that initiative easier.

The functional changes on this PR are essentially:
- Adding a new property to CloudLineBreakpointProperties: addedOnServer;
- Checking for that property on CloudBreakpointHandler.registerBreakpoint();
- Unit tests.

**Comment by patflynn** [comment]
I'm fine with restyling as you go, as long as it's relatively easy for the
reviewer to identify the real changes.

Agreed that a full project reformat is in order.  There's an issue filed
for this. It should be done soon, probably over a weekend to minimize
disruption to other CLs in flight.

File: core-plugin/src/com/google/gct/idea/debugger/CloudBreakpointHandler.java (hunk 5 above)
Comment (joaoandremartins) [inline core-plugin/src/com/google/gct/idea/debugger/CloudBreakpointHandler.java]: It seems correctly indented to me. What indentation do you suggest?

**Comment by joaoandremartins** [comment]
PTAL

File: core-plugin/src/com/google/gct/idea/debugger/CloudBreakpointHandler.java [hunk 6]
```diff
@@ -49,22 +49,27 @@
...
- * cloudIdeBreakpoint: these are our IDE defined customized breakpoints
- *                 {@link com.google.gct.idea.debugger.CloudLineBreakpointType.CloudLineBreakpoint} with
- *                 custom properties, etc. It's confusing that there are two hierarchies for IDE breakpoints,
- *                 but intelliJ does this to control some base behavior.
- * serverBreakpoint: these are the {@link Breakpoint} breakpoints our server gives us via the apiary api.
+ * The Cloud Debugger breakpoint handler is responsible for creating or deleting the breakpoints on
+ * the server. It is responsible for creating local IDE representations given a server
+ * representation. It stores a relationship between the local IDE representation and the server
+ * breakpoint and provides methods for getting one given the other. {@link XBreakpointHandler} is
+ * often called by intelliJ when the user enables or disables breakpoints.
```
Comment (elharo) [inline core-plugin/src/com/google/gct/idea/debugger/CloudBreakpointHandler.java]: IntelliJ

File: core-plugin/src/com/google/gct/idea/debugger/CloudBreakpointHandler.java [hunk 7]
```diff
@@ -49,22 +49,27 @@
...
+ *
+ * <p/>This class is threadsafe. All operations can be called by multiple threads.
+ *
+ * <p>Note there are three breakpoint types managed in the debugger and are named to avoid
+ * confusion:
+ * <ul>
+ * <li>xIdeBreakpoint : these are {@link XBreakpoint} types that intelliJ defines and are sealed.
```
Comment (elharo) [inline core-plugin/src/com/google/gct/idea/debugger/CloudBreakpointHandler.java]: asterisks are redundant with <li>

File: core-plugin/src/com/google/gct/idea/debugger/CloudBreakpointHandler.java [hunk 8]
```diff
@@ -49,22 +49,27 @@
...
+ * <li>cloudIdeBreakpoint: these are our IDE defined customized breakpoints
+ *                 {@link com.google.gct.idea.debugger.CloudLineBreakpointType.CloudLineBreakpoint}
+ *                 with custom properties, etc. It's confusing that there are two hierarchies for
+ *                 IDE breakpoints, but intelliJ does this to control some base behavior.
```
Comment (elharo) [inline core-plugin/src/com/google/gct/idea/debugger/CloudBreakpointHandler.java]: IntelliJ

File: core-plugin/src/com/google/gct/idea/debugger/CloudBreakpointHandler.java [hunk 9]
```diff
@@ -330,13 +349,18 @@ public void registerBreakpoint(@NotNull final XLineBreakpoint<CloudLineBreakpoin
...
       // This newly created IDE breakpoint could be the result of syncing with the server state,
-      // in which case, there is nothing
-      // to do.  Just return.
+      // in which case, there is nothing to do.  Just return.
       // Note that we need to implement this flag as a transient property because this method
       // gets called during construction.
       return;
     }
 
+    if (xIdeBreakpoint.getProperties().isAddedOnServer()) {
```
Comment (patflynn) [inline core-plugin/src/com/google/gct/idea/debugger/CloudBreakpointHandler.java]: why is a breakpoint that has already been successfully added being passed to registreBreakpoint in the first place?

File: core-plugin/src/com/google/gct/idea/debugger/CloudBreakpointHandler.java (hunk 5 above)
Comment (elharo) [inline core-plugin/src/com/google/gct/idea/debugger/CloudBreakpointHandler.java]: nvm, you're right. I misread it.

**Comment by elharo** [comment]
lgtm

File: core-plugin/src/com/google/gct/idea/debugger/CloudBreakpointHandler.java (hunk 9 above)
Comment (joaoandremartins) [inline core-plugin/src/com/google/gct/idea/debugger/CloudBreakpointHandler.java]: When the breakpoint is added successfully and hit offline, IJ doesn't know it was hit. When you resume the session after the breakpoint is hit, IJ registers every _enabled_ breakpoint with the server. Since IJ didn't know the breakpoint was hit, it didn't mark it as disabled and the breakpoint is therefore registered again.
