### PR TITLE
fix platform dependent unit tests

### LINKED ISSUE #510: A bunch of MVM test cases fail when run on Windows
com.google.gct.idea.appengine.cloud.ManagedVmCloudConfigurableTest > testApply_validSdkAndInvalidProject FAILED
    junit.framework.ComparisonFailure at ManagedVmCloudConfigurableTest.java:112

com.google.gct.idea.appengine.cloud.ManagedVmCloudConfigurableTest > testSetupWithSdkInPath FAILED
    junit.framework.ComparisonFailure at ManagedVmCloudConfigurableTest.java:80

com.google.gct.idea.appengine.cloud.ManagedVmCloudConfigurableTest > testApply_validSdkAndValidProject FAILED
    com.intellij.execution.configurations.RuntimeConfigurationError at ManagedVmCloudConfigurableTest.java:100

com.google.gct.idea.appengine.util.CloudSdkUtilTest > testPaths FAILED
    org.junit.ComparisonFailure at CloudSdkUtilTest.java:53

com.google.gct.idea.appengine.util.CloudSdkUtilTest > testDirExecutableConversion FAILED
    org.junit.ComparisonFailure at CloudSdkUtilTest.java:70

### PR DESCRIPTION
**Pull request by etanshaul**
fixes #510

### CODE REVIEW

File: google-cloud-tools-plugin/testSrc/com/google/gct/idea/appengine/cloud/AppEngineCloudConfigurableTest.java [hunk 1]
```diff
@@ -43,8 +44,8 @@
   private JLabel warningMessage;
   private TextFieldWithBrowseButton cloudSdkDirectoryField;
 
-  private static final String CLOUD_SDK_EXECUTABLE_PATH = "/a/b/c/gcloud-sdk/bin/gcloud";
-  private static final String CLOUD_SDK_DIR_PATH = "/a/b/c/gcloud-sdk";
+  private static final String CLOUD_SDK_EXECUTABLE_PATH = new File("/a/b/c/gcloud-sdk/bin/gcloud").getAbsolutePath();
```
Comment (meltsufin) [inline google-cloud-tools-plugin/testSrc/com/google/gct/idea/appengine/cloud/AppEngineCloudConfigurableTest.java]: This might work too: "/a/b/c/gcloud-sdk/bin/gcloud".replace("/", File.pathSeparator)

**Comment by patflynn** [comment]
Ask Valentin for a Windows laptop! :)

**Comment by etanshaul** [comment]
As much as I trust the Windows emulator in my head, that's what I did :) Already tested on a win laptop.

**Comment by etanshaul** [comment]
@patflynn any comments on this one?

File: google-cloud-tools-plugin/testSrc/com/google/gct/idea/appengine/cloud/AppEngineCloudConfigurableTest.java [hunk 2]
```diff
@@ -155,7 +156,7 @@ private void initCloudConfigurable() {
   private File createTempFile() throws IOException {
     TemporaryFolder tempFolder = new TemporaryFolder();
     tempFolder.create();
-    File executable = new File(tempFolder.newFolder("bin"), "gcloud");
+    File executable = new File(tempFolder.newFolder("bin"), SystemInfo.isWindows ? "gcloud.cmd" : "gcloud");
```
Comment (patflynn) [inline google-cloud-tools-plugin/testSrc/com/google/gct/idea/appengine/cloud/AppEngineCloudConfigurableTest.java]: this code seems to be factored out in the CloudSdkUtilTest.  Also do we do this anywhere in the non-test code?

Comment (meltsufin) [inline google-cloud-tools-plugin/testSrc/com/google/gct/idea/appengine/cloud/AppEngineCloudConfigurableTest.java]: I don't see any other references. If you make CloudSdkUtil.getSystemCommand() public, you can avoid the duplication of this check.

Comment (patflynn) [inline google-cloud-tools-plugin/testSrc/com/google/gct/idea/appengine/cloud/AppEngineCloudConfigurableTest.java]: sounds like a good idea.

Comment (etanshaul) [inline google-cloud-tools-plugin/testSrc/com/google/gct/idea/appengine/cloud/AppEngineCloudConfigurableTest.java]: Sure I can do that. My thought process was that having the duplication in the unit tests asserts that we have those commands correct in the actual code. Kind of in the same way that its a good idea to duplicate properties from our message bundle in the unit tests rather than referring to them directly. What do you guys think?

Comment (patflynn) [inline google-cloud-tools-plugin/testSrc/com/google/gct/idea/appengine/cloud/AppEngineCloudConfigurableTest.java]: If you want to verify the logic of the cross platform command resolution,
I'd rather we have an explicit test for that.  I don't really buy into the
idea that duplication as a testing failsafe is worth the cost.

Comment (etanshaul) [inline google-cloud-tools-plugin/testSrc/com/google/gct/idea/appengine/cloud/AppEngineCloudConfigurableTest.java]: Makes sense to me. Updated.

File: google-cloud-tools-plugin/src/com/google/gct/idea/appengine/util/CloudSdkUtil.java [hunk 3]
```diff
@@ -117,6 +117,10 @@ public static String toSdkHomeDirectory(String sdkExecutablePath) {
     return null;
   }
 
+  public static String getSystemCommand() {
```
Comment (patflynn) [inline google-cloud-tools-plugin/src/com/google/gct/idea/appengine/util/CloudSdkUtil.java]: let's add a test for this method now :).

Otherwise LGTM.

Comment (etanshaul) [inline google-cloud-tools-plugin/src/com/google/gct/idea/appengine/util/CloudSdkUtil.java]: No to dwell on this too much, but it was a pretty weird test to write (given that there's no ready way to mock SystemInfo and I'm not sure that's worth the effort). It basically just duplicates the code in the unit test:

 ``` 
 @Test
  public void testSystemDependentCommand() {
    String systemCommand = SystemInfo.isWindows ? WIN_COMMAND : UNIX_COMMAND;
    assertEquals(systemCommand, CloudSdkUtil.getSystemCommand());
  }
```

Comment (etanshaul) [inline google-cloud-tools-plugin/src/com/google/gct/idea/appengine/util/CloudSdkUtil.java]: Nevermind I could easily mock SystemInfo by adding an adapter in SystemEnvironmentProvider (that's why I made this class anyway).

Comment (etanshaul) [inline google-cloud-tools-plugin/src/com/google/gct/idea/appengine/util/CloudSdkUtil.java]: Sorry for all the chatter on this. I think its not worth the extra baggage of passing the environmentProvider around in more places just to test that method (which all the test would do is assert that our constants are written correctly). Also having a test like the snippet I pasted above feels flaky to me. So I'll just leave this test out if that sounds ok.

**Comment by patflynn** [comment]
Ah that sucks.  More static nastiness.  Leave it as is then. Thanks for trying.

**Comment by patflynn** [comment]
LGTM
