### PR TITLE
fix datetime pattern for version generation

### LINKED ISSUE #596: Generated version time stamp for App Engine deployment does not match the the Cloud SDK
capture

### PR DESCRIPTION
**Pull request by etanshaul**
fixes #596 

Updated the pattern to use 2 digit versions for hours, min, seconds. Thinking about ways to create non-flaky unit tests for this.

### CODE REVIEW

**Comment by patflynn** [comment]
lgtm

**Comment by etanshaul** [comment]
added a couple tests

File: google-cloud-tools-plugin/testSrc/com/google/cloud/tools/intellij/appengine/util/AppEngineUtilTest.java [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+import org.junit.Test;
+
+/**
+ * Tests App Engine Utilities
+ * Uses an external trusted datetime to milli converter to set the datetime to the desired value.
+ */
+public class AppEngineUtilTest {
+
+  @Test
+  public void testDateTimeToVersion() {
```
Comment (patflynn) [inline google-cloud-tools-plugin/testSrc/com/google/cloud/tools/intellij/appengine/util/AppEngineUtilTest.java]: Typically the way we handle this internally is by using a clock class internally that either uses real time or is mocked ofr tests.

Comment (etanshaul) [inline google-cloud-tools-plugin/testSrc/com/google/cloud/tools/intellij/appengine/util/AppEngineUtilTest.java]: Could you explain a bit? If I use a clock internally with real time then the test feels a bit flaky to me because it depends on when the test is run. If the clock is set to a preconfigured datetime then the problem is circular because it would require using a formatter to set it (which is what we are testing in the first place). I tried mocking DateTime but didn't have much luck with that approach.

Comment (patflynn) [inline google-cloud-tools-plugin/testSrc/com/google/cloud/tools/intellij/appengine/util/AppEngineUtilTest.java]: To make this work properly I think you'll have to make an
AppEngineVersionGenerator(Clock)  where for tests you can provide a mock
Clock that returns the instant that specifies some fixed point in time you
can test against.  Or actually I think you can pass a fixed time Clock as
well.

Comment (etanshaul) [inline google-cloud-tools-plugin/testSrc/com/google/cloud/tools/intellij/appengine/util/AppEngineUtilTest.java]: updated

**Comment by patflynn** [comment]
LGTM. We can start using Clock when we move to Java 8, or introduce our own should it become a problem.
