### PR TITLE
Save and load artifact deployment source types

### LINKED ISSUE #729: Artifact deployment source not deserialized on reboot
Steps:
1) Create a deployment run config with an Artifact type as the deployment source and save it.
2) Reboot the IDE
3) Attempt to run the previously created configuration
=> Stack trace (java.lang.RuntimeException: Invalid deployment source selected for deployment)

### PR DESCRIPTION
**Pull request by etanshaul**
fixes #729 

@patflynn, @chanseokoh 

This error occurs when deployment configurations containing an AE artifact deployment sources are created. Once these configurations are created, if the user closes the project and then attempts to reload the configuration, this fix will correctly recreate the artifact from the serialized state that was saved by the IDE. Without this fix, the `AppEngineArtifactDeploymentSource` will not be recreated - only its platform supplied superclass - which will miss out on AE specific details such as environment, and cause downstream errors during deployment.

### CODE REVIEW

File: google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/AppEngineArtifactDeploymentSourceType.java [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+          }
+        }
+    );
+
+    Element settings = tag.getChild(DeployToServerRunConfiguration.SETTINGS_ELEMENT);
+
+    if (artifact.isPresent() && settings != null) {
+      String environment = settings.getAttributeValue(
+          AppEngineDeploymentConfiguration.ENVIRONMENT_ATTRIBUTE);
+
```
Comment (patflynn) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/AppEngineArtifactDeploymentSourceType.java]: don't we resolve environment based off of the artifact in the normal flow?  Why are we storing it for the deserialization flow?

**Comment by patflynn** [comment]
The link to the error is helpful, but it would also be nice to describe what was the underlying cause and how this fixes it.

File: google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/AppEngineArtifactDeploymentSourceType.java (hunk 1 above)
Comment (etanshaul) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/AppEngineArtifactDeploymentSourceType.java]: good point. I think that we can use the normal flow here too. I'll refactor it.

**Comment by etanshaul** [comment]
Which link do you mean? Do you mean add a description in the PR? If so, no problem.

**Comment by patflynn** [comment]
Yeah sorry. I meant that the link to the issue was helpful, but it doesn't
really say what the underlying problem was, so the PR should provide a bit
of context.

File: google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/AppEngineArtifactDeploymentSourceType.java [hunk 2]
```diff
@@ -0,0 +1,85 @@
...
+      return new AppEngineArtifactDeploymentSource(
+          AppEngineEnvironment.valueOf(environment),
+          ArtifactPointerManager.getInstance(project).createPointer(artifact.get()));
+    } else {
+      return new AppEngineArtifactDeploymentSource(
+          ArtifactPointerManager.getInstance(project)
+              .createPointer(tag.getAttributeValue(NAME_ATTRIBUTE)));
+    }
```
Comment (chanseokoh) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/AppEngineArtifactDeploymentSourceType.java]: Can we use just `name` in place of `tag.getAttributeValue(NAME_ATTRIBUTE)`? Possibly with an elaborated variable name.

File: google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/AppEngineArtifactDeploymentSourceType.java [hunk 3]
```diff
@@ -0,0 +1,85 @@
...
+        new Predicate<Artifact>() {
+          @Override
+          public boolean apply(Artifact artifact) {
+            return artifact.getName().equals(name);
+          }
+        }
+    );
+
+    Element settings = tag.getChild(DeployToServerRunConfiguration.SETTINGS_ELEMENT);
+
```
Comment (chanseokoh) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/AppEngineArtifactDeploymentSourceType.java]: Seems like we can skip the above `tryFind` search if we check `settings != null` first (unless this kind of refactoring makes code more complex).

Comment (etanshaul) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/AppEngineArtifactDeploymentSourceType.java]: Maybe I didn't catch your point, but the tryFind is to filter our our target Artifact from the list (it returns the first that matches the predicate).

Comment (chanseokoh) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/AppEngineArtifactDeploymentSourceType.java]: Sorry, let me put this way. I mean in the current logic, if `settings == null`, it will always take the `else` branch (note this branch doesn't use `artifact`) regardless of the outcome of `artifact`. So, if we need to do tryFind only when `settings != null`.

Comment (etanshaul) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/AppEngineArtifactDeploymentSourceType.java]: I see. thanks.

File: google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/AppEngineArtifactDeploymentSourceType.java (hunk 2 above)
Comment (etanshaul) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/AppEngineArtifactDeploymentSourceType.java]: yes. I'll update this too.

File: google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/AppEngineArtifactDeploymentSourceType.java (hunk 1 above)
Comment (etanshaul) [inline google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/AppEngineArtifactDeploymentSourceType.java]: I think this actually might not be the way to do it. In order to get the environment via the "normal" flow (for AE standard artifacts) it has to perform a check for the existence of the app engine facet. 

The problem is that this deserialization logic happens before the facet is loaded.

**Comment by etanshaul** [comment]
@chanseokoh refactored based on your comments

**Comment by patflynn** [comment]
@etanshaul That's weird.  Run configs are not dumb aware so the project state should be available.

**Comment by etanshaul** [comment]
Yea. I'm looking at it more carefully to confirm. Also I added a description of the problem to the first PR comment.

**Comment by etanshaul** [comment]
@patflynn So if even though its not dumb aware it has to do with the order of the loading. At the time this configuration is deserialized, the project's modules have even been loaded yet.

**Comment by patflynn** [comment]
that's odd. The artifacts have loaded but the modules haven't?

**Comment by etanshaul** [comment]
Agree its odd. But its exactly what I'm seeing. I guess its just as valid to do it in that order (establish the link from the modules after the artifacts have been loaded).

**Comment by patflynn** [comment]
Thank you for the updated description1

**Comment by patflynn** [comment]
@etanshaul is there a risk that the environment should be different at deserialization from what it was at serialization?

**Comment by etanshaul** [comment]
I was about to say that there isn't (because what gets serialized is the results of the full blown environment resolution logic). 

But I realized that a Deployment Configuration can contain multiple artifacts - each with potentially different environments - and I am only persisting a single environment. I need to investigate this aspect. Thanks for asking that question.

**Comment by etanshaul** [comment]
False alarm on my last comment:

It works the same way as any of the other fields, like version for example (which can be different for every source). I think it stores the configuration for each source.

To answer your original question again: I don't see any risk here.
