### PR TITLE
Fixes Cloud Repos error messaging.

### LINKED ISSUE #249: Cloud Repo checkout hides key fields when parent directory is modified
screenshot from 2015-12-01 16 29 51

Steps:
1) Start IJ with the CT plugin installed
2) Checkout project from Cloud Repos
3) login and pick a project
4) modify the parent project path

observe that the UI for the project directory disappears.

### PR DESCRIPTION
**Pull request by joaoandremartins**
Fixes #249 @elharo @patflynn

### CODE REVIEW

**Comment by joaoandremartins** [comment]
I signed it!

**Comment by joaoandremartins** [comment]
I signed it!

**Comment by elharo** [comment]
Don't worry about the cla thing. Since you're an employee I think we just need to add you as a member of the right group. I'll see if I can figure this out when I'm back in the office on 12/28.

File: core-plugin/src/com/google/gct/idea/git/CloneGcpDialog.java [hunk 1]
```diff
@@ -206,4 +208,22 @@ public JComponent getPreferredFocusedComponent() {
...
+    parentDirectoryLabel.setForeground(Color.black);
+  }
+
+  /**
+   * Activates when a user selection is incorrect.
+   *
+   * Paints the "Parent Directory" label and textbox background red.
+   */
+  private void paintSelectionError() {
+    myParentDirectory.setBackground(Color.red);
```
Comment (elharo) [inline core-plugin/src/com/google/gct/idea/git/CloneGcpDialog.java]: Color.RED for conformance iwth naming conventions. (Sun got this wrong in the early days and corrected it in 1.4.)

File: core-plugin/resources/messages/CloudToolsBundle.properties [hunk 2]
```diff
@@ -26,13 +26,13 @@ appengine.run.no.gradle.state=App Engine Gradle configuration does not appear to
 
 appengine.sdk.invalid=A valid App Engine SDK was not found for module : {0}.
 
-clonefromgcp.projectid=Cloud Project
+clonefromgcp.projectid=Cloud Project\:
```
Comment (elharo) [inline core-plugin/resources/messages/CloudToolsBundle.properties]: What does the colon mean if you don't backslash it here?

**Comment by elharo** [comment]
Joao, 

Please run this command in your git client and repush:

 git config --global user.email "joaomartins@google.com"

That should take care of the cla check. If it doesn't, holler and I can merge it. But is should definitely fix any merges going forward.

File: core-plugin/resources/messages/CloudToolsBundle.properties (hunk 2 above)
Comment (joaoandremartins) [inline core-plugin/resources/messages/CloudToolsBundle.properties]: I thought I'd backslashed it because it didn't show, but in my Mac it's always showing, so I'll just remove the backslash.

**Comment by joaoandremartins** [comment]
@elharo I ran the command, but the cla check won't move. Are you able to merge?

**Comment by elharo** [comment]
cla check is still running; if it fails again I can merge this

**Comment by elharo** [comment]
Can you squash your commits?

**Comment by loosebazooka** [comment]
In general I think it's a good idea for us to avoid commits like "Merge branch 'master' into dialog-spacing"
Rebasing on your development machine would probably have been the preferred mechanism here.

**Comment by joaoandremartins** [comment]
@loosebazooka I rebased locally. Do you mean to say I should have merged master with my branch locally too? (This commit was triggered by my clicking the "Update branch" button in git, we might want to remove or not click it)

**Comment by loosebazooka** [comment]
Yeah, I think the recommended mechanism should be to not allow clicking it, I'll see if we can remove that button.
