### PR TITLE
Fix issue with storing and retrieving OAuth data

### LINKED ISSUE #601: Corrupted saved credentials cause false logged in state
The error I get in the IntelliJ Event Log is:

> IllegalArgumentException: Argument for @NotNull parameter 'userEmail' of com/google/cloud/tools/intellij/login/CredentialedUserRoster.setActiveUser must not be null

It appears that the Account Plugin saved a corrupted authentication state where everything is null except for the refreshToken. The end result is that the account plugin thinks the user is logged in, but it causes failures because it doesn't have all of the needed user information.

### PR DESCRIPTION
**Pull request by meltsufin**
Fixes #601 

When the user's email address is null, we need to be careful with storing and reading the saved OAuth data because it's keyed on the email address.

I'm still not sure how I ended up with OAuth data stored in Preferences keyed on a null email address in the first place. However, with these changes it should never happen because we will always check that the email address is not null before storing OAuth data.

Also, this change ensures that we only try to read OAuth data when a user is logged in and hence has an associated email address. So, even with the corrupted prefs.xml file, everything should be fine after this change. I tested with the bad prefs.xml file referenced in the issue.

### CODE REVIEW

**Comment by etanshaul** [comment]
Trying to wrap my head around this one: So after these changes, if the user reproduces the original issue, they will be just be logged out with no errors? In other words, if the user is logged in and their auth settings are corrupted (somehow) then what exactly happens?

**Comment by meltsufin** [comment]
After these changes it would not be possible to reproduce the original issue because we're now guarding against saving invalid OAuth data. So, we will never be in a situation where we will be attempting to load invalid OAuth data.

I'm still not entirely sure about the situation which causes the auth tokens to be set while the user email is null. I suspect that happens when the user is logged out for a reason like session timeout and cleanup is not done fully. In that situation the only thing that will be different is that these invalid OAuth session settings will no be saved. The login status will remain unchanged.

File: google-account-plugin/src/com/google/cloud/tools/intellij/login/GoogleLoginPrefs.java [hunk 1]
```diff
@@ -82,17 +86,23 @@ public static void saveOAuthData(OAuthData credentials) {
...
-    String storedEmail = prefs.get(getCustomUserKey(OAUTH_DATA_EMAIL_KEY), null);
-    String storedScopesString = prefs.get(getCustomUserKey(OAUTH_SCOPES_KEY), "");
+    if (Services.getLoginService().getActiveUser() != null) {
+      Preferences prefs = getPrefs();
 
-    // Use a set to ensure uniqueness.
-    SortedSet<String> storedScopes = new TreeSet<String>();
-    for (String scope : storedScopesString.split(DELIMITER)) {
-      storedScopes.add(scope);
+      refreshToken = prefs.get(getCustomUserKey(OAUTH_DATA_REFRESH_TOKEN_KEY), null);
```
Comment (patflynn) [inline google-account-plugin/src/com/google/cloud/tools/intellij/login/GoogleLoginPrefs.java]: My guess is a bunch of this code is the way it is because the original credential store did not support multiple users and this tries to support both the schema with just one user, and the one with a list of users and an active user.

File: google-account-plugin/src/com/google/cloud/tools/intellij/login/GoogleLoginPrefs.java [hunk 2]
```diff
@@ -82,17 +86,23 @@ public static void saveOAuthData(OAuthData credentials) {
...
   public static OAuthData loadOAuthData() {
-    Preferences prefs = getPrefs();
+    String refreshToken = null;
+    String storedEmail = null;
+    SortedSet<String> storedScopes = new TreeSet<String>();
 
-    String refreshToken = prefs.get(getCustomUserKey(OAUTH_DATA_REFRESH_TOKEN_KEY), null);
-    String storedEmail = prefs.get(getCustomUserKey(OAUTH_DATA_EMAIL_KEY), null);
-    String storedScopesString = prefs.get(getCustomUserKey(OAUTH_SCOPES_KEY), "");
+    if (Services.getLoginService().getActiveUser() != null) {
```
Comment (patflynn) [inline google-account-plugin/src/com/google/cloud/tools/intellij/login/GoogleLoginPrefs.java]: one of the big problems in the design of this library is the two sources of state of active user.

File: google-account-plugin/src/com/google/cloud/tools/intellij/login/GoogleLoginPrefs.java [hunk 3]
```diff
@@ -82,17 +86,23 @@ public static void saveOAuthData(OAuthData credentials) {
    * an {@code OAuthData} object all of whose getters return {@code null} .
    */
   public static OAuthData loadOAuthData() {
-    Preferences prefs = getPrefs();
+    String refreshToken = null;
+    String storedEmail = null;
+    SortedSet<String> storedScopes = new TreeSet<String>();
```
Comment (patflynn) [inline google-account-plugin/src/com/google/cloud/tools/intellij/login/GoogleLoginPrefs.java]: looking at the javadoc it seems to indicate that all getters should be null when there is no active user.

Comment (patflynn) [inline google-account-plugin/src/com/google/cloud/tools/intellij/login/GoogleLoginPrefs.java]: I guess the old code returns the empty set, so it makes sense not to change  that behavior.

**Comment by patflynn** [comment]
LGTM
